with unpivot_medical_claims as (

    {{ dbt_utils.unpivot(
      relation=ref('base_ssm__claim_header'),
      exclude=['identifier_claim_header',
               'patient',
               'billable_period_start',
               'lob',
               'insurer',
               'client_id',
               'ingest_date'],
      remove=['subscriber_id',
              'dependent_number',
              'place_of_service',
              'sub_type',
              'service_date_time',
              'billable_period_end',
              'admission_type',
              'admission_source',
              'discharge_status',
              'rev_code',
              'drg',
              'first_name',
              'last_name',
              'gender',
              'date_of_birth',
              'procedure_code1',
              'procedure_code2',
              'procedure_code3',
              'procedure_code4',
              'procedure_code5',
              'procedure_code6',
              'procedure_code7',
              'procedure_code8',
              'procedure_code9',
              'procedure_code10',
              'procedure_code11',
              'procedure_code12',
              'procedure_code13',
              'procedure_code14',
              'procedure_code15',
              'procedure_code16',
              'procedure_code17',
              'procedure_code18',
              'procedure_code19',
              'procedure_code20',
              'procedure_code1_modifier',
              'procedure_code2_modifier',
              'procedure_code3_modifier',
              'procedure_code4_modifier',
              'procedure_code5_modifier',
              'procedure_code6_modifier',
              'procedure_code7_modifier',
              'procedure_code8_modifier',
              'procedure_code9_modifier',
              'procedure_code10_modifier',
              'procedure_code11_modifier',
              'procedure_code12_modifier',
              'procedure_code13_modifier',
              'procedure_code14_modifier',
              'procedure_code15_modifier',
              'procedure_code16_modifier',
              'procedure_code17_modifier',
              'procedure_code18_modifier',
              'procedure_code19_modifier',
              'procedure_code20_modifier',
              'icd_version_indicator',
              'allowed_amount',
              'charge_amount',
              'payment_date_time',
              'total',
              'member_payment_amount',
              'claim_adjustment_type_code',
              'claim_adjustment_sequence_number',
              'claim_adjustment_date_time',
              'provider',
              'rendering_provider_npi',
              'referring_provider_npi',
              'pcp_provider_npi',
              'facility',],
      field_name='sequence',
      value_name='code'
      ) }}

),

final as (

    select distinct {{ dbt_utils.surrogate_key(['identifier_claim_header',
                                                'patient',
                                                'code']) }} as identifier_condition,
                    patient as identifier_external_source,
                    identifier_claim_header as encounter,
                    billable_period_start as recorded_date,
                    'claim' as category_code,
                    code,
                    'ICD-10' as code_system,
                    null::date as onset_datetime,
                    null::date as abatement_datetime,
                    client_id,
                    ingest_date

    from unpivot_medical_claims
    where code is not null

)

SELECT *
FROM final
