version: 2

models:
  - name: base_humana__referral
    description: Base Humana members
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - identifier_strive_id
            - ingest_date
    columns:
      - name: identifier_strive_id
        description: Strive Unique Identifier
        tests:
          - not_null

      - name: identifier_external_subscriber_id
        description: Humana member ID. Also referred to as `mbr_pers_gen_key` or `pers_gen_key`
        tests:
          - not_null

      - name: given_first_name
        description: Member first name
        tests:
          - not_null

      - name: family_name
        description: Member last name
        tests:
          - not_null

      - name: birth_date
        description: Member birth date
        tests:
          - is_date:
              date_format: yyyy-mm-dd

      - name: gender
        description: Member gender

      - name: telecom_home_phone_number
        description: Member home phone number

      - name: telecom_work_phone_number
        description: Member work phone number

      - name: telecom_email_address
        description: Member email address

      - name: address_line1
        description: Member address line 1

      - name: address_line2
        description: Member address line 2

      - name: address_city
        description: Member address city
      
      - name: address_state
        description: Member address state

      - name: address_postal_code
        description: Address postal code

      - name: address_district
        description: Address county

      - name: general_practitioner
        description: Member primary care physician (PCP)

      - name: client_id
        description: Strive client ID
        tests:
          - not_null
          - accepted_values:
              values: ['humana']

      - name: ingest_date
        description: Most recent ingest date
        tests:
          - not_null
          - is_date:
              date_format: yyyy-mm-dd HH24:MI:SS

  - name: base_humana__demographics
    description: Base Humana demographics
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - identifier_strive_id
            - ingest_date
    columns:
      - name: identifier_strive_id
        description: Strive Unique Identifier
        tests:
          - not_null

      - name: deceased_date
        description: Member deceased date

      - name: client_id
        description: Strive client ID
        tests:
          - not_null
          - accepted_values:
              values: ['humana']

      - name: ingest_date
        description: Most recent ingest date
        tests:
          - not_null
          - is_date:
              date_format: yyyy-mm-dd HH24:MI:SS
