WITH source AS (

    SELECT ROW_NUMBER() OVER(PARTITION BY medclm_key
                             ORDER BY ingest_date DESC) AS row_num,
           *
    FROM {{ source('humana_src','medical_claims') }}

),

source_renamed AS (

    SELECT {{ empty_string_to_null('admit_diag_cd') }} AS admit_diag_cd,
           {{ empty_string_to_null('admit_src_cd') }} AS admit_src_cd,
           {{ empty_string_to_null('allow_icob_admit_cnt') }} AS allow_icob_admit_cnt,
           {{ empty_string_to_null('allow_icob_amt') }} AS allow_icob_amt,
           {{ empty_string_to_null('allow_icob_days_cnt') }} AS allow_icob_days_cnt,
           {{ empty_string_to_null('allow_icob_visits_cnt') }} AS allow_icob_visits_cnt,
           {{ empty_string_to_null('bill_type_cd') }} AS bill_type_cd,
           DATE(medclm_lclm_to_date) AS billable_period_end,
           DATE(medclm_lclm_from_date) AS billable_period_start,
           chrg_amt::numeric(18,2) AS chrg_amt,
           {{ empty_string_to_null('chrg_days_cnt') }} AS chrg_days_cnt,
           {{ empty_string_to_null('clm_aso_ind') }} AS clm_aso_ind,
           {{ empty_string_to_null('cob_paid_amt') }} AS cob_paid_amt,
           {{ empty_string_to_null('copay_amt') }} AS copay_amt,
           {{ empty_string_to_null('cov_month') }} AS cov_month,
           {{ empty_string_to_null('ctrct_cat_cd') }} AS ctrct_cat_cd,
           {{ empty_string_to_null('deduct_amt') }} AS deduct_amt,
           {{ empty_string_to_null('diag_cd2') }} AS diag_cd2,
           {{ empty_string_to_null('diag_cd3') }} AS diag_cd3,
           {{ empty_string_to_null('diag_cd4') }} AS diag_cd4,
           {{ empty_string_to_null('diag_cd5') }} AS diag_cd5,
           {{ empty_string_to_null('diag_cd6') }} AS diag_cd6,
           {{ empty_string_to_null('diag_cd7') }} AS diag_cd7,
           {{ empty_string_to_null('diag_cd8') }} AS diag_cd8,
           {{ empty_string_to_null('diag_cd9') }} AS diag_cd9,
           {{ empty_string_to_null('diag_cd10') }} AS diag_cd10,
           {{ empty_string_to_null('diag_cd11') }} AS diag_cd11,
           {{ empty_string_to_null('diag_cd12') }} AS diag_cd12,
           {{ empty_string_to_null('diag_cd13') }} AS diag_cd13,
           {{ empty_string_to_null('diag_cd14') }} AS diag_cd14,
           {{ empty_string_to_null('diag_cd15') }} AS diag_cd15,
           {{ empty_string_to_null('diag_cd16') }} AS diag_cd16,
           {{ empty_string_to_null('diag_cd17') }} AS diag_cd17,
           {{ empty_string_to_null('diag_cd18') }} AS diag_cd18,
           {{ empty_string_to_null('diag_cd19') }} AS diag_cd19,
           {{ empty_string_to_null('diag_cd20') }} AS diag_cd20,
           {{ empty_string_to_null('diag_cd21') }} AS diag_cd21,
           {{ empty_string_to_null('diag_cd22') }} AS diag_cd22,
           {{ empty_string_to_null('diag_cd23') }} AS diag_cd23,
           {{ empty_string_to_null('diag_cd24') }} AS diag_cd24,
           {{ empty_string_to_null('diag_cd25') }} AS diag_cd25,
           {{ empty_string_to_null('dischg_stat_cd') }} AS dischg_stat_cd,
           {{ empty_string_to_null('drg_lclm_cd') }} AS drg_lclm_cd,
           {{ empty_string_to_null('fin_prod_cd') }} AS fin_prod_cd,
           {{ empty_string_to_null('icd_proc_01_cd') }} AS icd_proc_01_cd,
           {{ empty_string_to_null('icd_proc_02_cd') }} AS icd_proc_02_cd,
           {{ empty_string_to_null('icd_proc_03_cd') }} AS icd_proc_03_cd,
           {{ empty_string_to_null('icd_proc_04_cd') }} AS icd_proc_04_cd,
           {{ empty_string_to_null('icd_proc_05_cd') }} AS icd_proc_05_cd,
           medclm_lclm_key AS identifier_claim_header,
           ROW_NUMBER() OVER(PARTITION BY medclm_lclm_key
                             ORDER BY medclm_key) AS identifier_claim_line,
           {{ dbt_utils.surrogate_key(['mbr_pers_gen_key']) }} AS identifier_strive_id,
           {{ empty_string_to_null('in_plan_ntwk_ind') }} AS in_plan_ntwk_ind,
           {{ empty_string_to_null('mbr_cost_shr_amt') }} AS mbr_cost_shr_amt,
           {{ empty_string_to_null('mco_contract_nbr') }} AS mco_contract_nbr,
           medclm_key,
           {{ empty_string_to_null('cpt_mod_cd') }} AS modifier_1,
           {{ empty_string_to_null('cpt_mod_cd2') }} AS modifier_2,
           {{ empty_string_to_null('ndc_id') }} AS ndc_id,
           {{ empty_string_to_null('net_paid_amt') }} AS net_paid_amt,
           {{ empty_string_to_null('net_paid_days_cnt') }} AS net_paid_days_cnt,
           {{ empty_string_to_null('paid_date') }} AS paid_date,
           {{ dbt_utils.surrogate_key(['mbr_pers_gen_key']) }} AS patient,
           {{ empty_string_to_null('pbp_segment_id') }} AS pbp_segment_id,
           {{ empty_string_to_null('plan_benefit_package_id') }} AS plan_benefit_package_id,
           {{ empty_string_to_null('pot_cd') }} AS pot_cd,
           {{ empty_string_to_null('primary_diag_cd') }} AS primary_diag_cd,
           {{ empty_string_to_null('hcpcs_cpt4_base_cd1') }} AS product_or_service,
           {{ empty_string_to_null('prov_tax_id') }} AS prov_tax_id,
           {{ empty_string_to_null('npi_id') }} AS provider,
           {{ empty_string_to_null('pymt_cat_cd') }} AS pymt_cat_cd,
           {{ empty_string_to_null('raw_clm_billg_prov_key') }} AS raw_clm_billg_prov_key,
           {{ empty_string_to_null('raw_clm_refr1_prov_key') }} AS raw_clm_refr1_prov_key,
           {{ empty_string_to_null('raw_clm_rendr_prov_key') }} AS raw_clm_rendr_prov_key,
           {{ empty_string_to_null('revenue_cd') }} AS revenue,
           DATE(serv_to_date) AS serviced_period_end,
           DATE(serv_from_date) AS serviced_period_start,
           serv_unit_cnt::numeric(18,2) AS quantity,
           {{ empty_string_to_null('src_admit_date') }} AS admit_datetime,
           {{ empty_string_to_null('src_dischrg_date') }} AS discharge_datetime,
           {{ empty_string_to_null('src_mbr_id') }} AS src_mbr_id,
           {{ empty_string_to_null('src_platform_cd') }} AS src_platform_cd,
           {{ empty_string_to_null('src_prov_specialty_cd') }} AS src_prov_specialty_cd,
           client_id,
           ingest_date

    FROM source
    WHERE row_num = 1

)

SELECT *
FROM source_renamed
