version: 2

models:
  - name: base_ssm__member
    description: Base SSM members
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - identifier_strive_id
            - ingest_date
    columns:
      - name: identifier_strive_id
        description: Strive Unique Identifier
        tests:
          - not_null

      - name: given_first_name
        description: Member first name
        tests:
          - not_null

      - name: given_middle_name
        description: Member middle name
        
      - name: family_name
        description: Member last name
        tests:
          - not_null

      - name: identifier_social_security_number
        description: Member social security number

      - name: birth_date
        description: Member birth date

      - name: identifier_external_subscriber_id
        description: Member SSM assigned patient ID

      - name: gender
        description: Member gender
      
      - name: race
        description: Member race

      - name: ethnic_group
        description: Member ethnic group
      
      - name: telecom_home_phone_number
        description: Member home phone number

      - name: telecom_email_address
        description: Member email address

      - name: address_line1
        description: Member address line 1

      - name: address_line2
        description: Member address line 2

      - name: address_city
        description: Member address city

      - name: address_state
        description: Member address state

      - name: address_postal_code
        description: Member address postal code

      - name: general_practitioner
        description: Member primary care physician

      - name: client_id
        description: Strive client ID
        tests:
          - not_null
          - accepted_values:
              values: ['ssm']

      - name: ingest_date
        description: Most recent ingest date
        tests:
          - not_null
          - is_date:
              date_format: yyyy-mm-dd HH24:MI:SS

  - name: base_ssm__patient
    description: Base SSM Patients
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - identifier_strive_id
            - ingest_date
    columns:
      - name: identifier_strive_id
        description: Strive Unique Identifier
        tests:
          - not_null

      - name: identifier_social_security_number
        description: Patient social security number

      - name: given_first_name
        description: Patient first name

      - name: family_name
        description: Patient last name

      - name: given_nickname
        description: Patient preferred name

      - name: name_prefix
        description: Patient name prefix

      - name: birth_date
        description: Patient birth date

      - name: gender
        description: Patient gender

      - name: race
        description: Patient race

      - name: language_preferred
        description: Patient primary spoken language

      - name: language_secondary
        description: Patient secondary language spoken

      - name: desceased_date
        description: Patient deceased date

      - name: birth_country
        description: Patient country of birth

      - name: address_line1
        description: Patient address line 1

      - name: address_line2
        description: Patient address line 2

      - name: address_city
        description: Patient address city

      - name: address_state
        description: Patient address state

      - name: address_postal_code
        description: Patient address postal code

      - name: address_postal_code_4
        description: Patient address postal code last 4

      - name: address_country
        description: Patient address country

      - name: address_type
        description: Patient address_type (e.g. home, work, etc.)

      - name: telecom_phone_number
        description: Patient phone number

      - name: telecom_phone_use
        description: Patient phone type (e.g. home, work, mobile, etc.)

      - name: telecom_email_address
        description: Patient email address

      - name: practitioner_identifier
        description: Practitioner ID

      - name: general_practitioner
        description: Patient primary care physician

      - name: client_id
        description: Strive client ID
        tests:
          - not_null
          - accepted_values:
              values: ['ssm']

      - name: ingest_date
        description: Most recent ingest date
        tests:
          - not_null
          - is_date:
              date_format: yyyy-mm-dd HH24:MI:SS 