version: 2

models:
  - name: base_ssm__member_eligibility
    description: Base SSM member/eligibility
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - identifier_strive_id
            - ingest_date
    columns:
      - name: identifier_strive_id
        description: Strive Unique Identifier
        tests:
          - not_null

      - name: name_given_first
        description: Member first name
        tests:
          - not_null

      - name: name_given_middle
        description: Member middle name
        
      - name: name_family
        description: Member last name
        tests:
          - not_null

      - name: identifier_social_security_number
        description: Member social security number

      - name: birth_date
        description: Member birth date

      - name: identifier_external_subscriber_id
        description: Member SSM assigned patient ID

      - name: gender
        description: Member gender
      
      - name: race
        description: Member race

      - name: ethnic_group
        description: Member ethnic group
      
      - name: telecom_phone_number_home
        description: Member home phone number

      - name: telecom_email_address
        description: Member email address

      - name: address_line1
        description: Member address line 1

      - name: address_line2
        description: Member address line 2

      - name: address_city
        description: Member address city

      - name: address_state
        description: Member address state

      - name: address_postal_code
        description: Member address postal code

      - name: general_practitioner
        description: Member primary care physician

      - name: period_coverage_start
        description: Coverage start date
        tests:
          - not_null
          - is_date:
              date_format: yyyy-mm-dd

      - name: period_coverage_end
        description: Coverage end date
        tests:
          - not_null
          - is_date:
              date_format: yyyy-mm-dd

      - name: relationship
        description: Member relationship to insurance policy holder

      - name: network
        description: Insurer network
        tests:
          - not_null

      - name: payor
        description: Insurer of the policy
        tests:
          - not_null

      - name: client_id
        description: Strive client ID
        tests:
          - not_null
          - accepted_values:
              values: ['ssm']

      - name: ingest_date
        description: Most recent ingest date
        tests:
          - not_null
          - is_date:
              date_format: yyyy-mm-dd HH24:MI:SS

  - name: base_ssm__crosswalk
    description: Base SSM Member Crosswalk
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - enterprise_mrn
            - person_id
            - lob
            - insurance_name
            - ingest_date
    columns:
      - name: enterprise_mrn
        description: Member's Enterprise Medical Record Number (MRN) assigned by SSM. This ID matches to the `patient_account_number` in the SSM clinical `patient` source
        tests:
          - not_null
      
      - name: person_id
        description: Crosswalk person_id. This ID matches the `patient_id` in the `member_eligibility` source
        tests:
            - not_null
      - name: lob
        description: Line of Business for Member's insurance provider
        tests:
          - not_null
      
      - name: insurance_name
        description: Member insurance name
        tests:
          - not_null

      - name: ingest_date
        description: Strive ingest date
        tests:
          - not_null
          - is_date:
              date_format: yyyy-mm-dd HH24:MI:SS

  - name: base_ssm__patient
    description: Base SSM Patients
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - identifier_strive_id
            - ingest_date
    columns:
      - name: identifier_strive_id
        description: Strive Unique Identifier
        tests:
          - not_null

      - name: identifier_social_security_number
        description: Patient social security number

      - name: name_given_first
        description: Patient first name

      - name: name_family
        description: Patient last name

      - name: name_given_nickname
        description: Patient preferred name

      - name: name_prefix
        description: Patient name prefix

      - name: birth_date
        description: Patient birth date

      - name: gender
        description: Patient gender

      - name: race
        description: Patient race

      - name: language_preferred
        description: Patient primary spoken language

      - name: language_secondary
        description: Patient secondary language spoken

      - name: desceased_date
        description: Patient deceased date

      - name: birth_country
        description: Patient country of birth

      - name: address_line1
        description: Patient address line 1

      - name: address_line2
        description: Patient address line 2

      - name: address_city
        description: Patient address city

      - name: address_state
        description: Patient address state

      - name: address_postal_code
        description: Patient address postal code

      - name: address_postal_code_4
        description: Patient address postal code last 4

      - name: address_country
        description: Patient address country

      - name: address_type
        description: Patient address_type (e.g. home, work, etc.)

      - name: telecom_phone_number
        description: Patient phone number

      - name: telecom_phone_use
        description: Patient phone type (e.g. home, work, mobile, etc.)

      - name: telecom_email_address
        description: Patient email address

      - name: practitioner_identifier
        description: Practitioner ID

      - name: general_practitioner
        description: Patient primary care physician

      - name: client_id
        description: Strive client ID
        tests:
          - not_null
          - accepted_values:
              values: ['ssm']

      - name: ingest_date
        description: Most recent ingest date
        tests:
          - not_null
          - is_date:
              date_format: yyyy-mm-dd HH24:MI:SS 

  - name: base_ssm__clinical_diagnoses
    description: Base SSM Clinical Diagnoses
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - patient_account_number
            - encounter
            - code
            - ingest_date
    columns:
      - name: patient_id
        description: Member ID assigned by SSM's Epic EHR. Matches to the `epic_pat_id` in the `member_crosswalk file

      - name: patient_account_number
        description: Member's Enterprise Medical Record Number (MRN) assigned by SSM. This ID matches to the `enterprise_mrn` in the SSM `member_crosswalk` source
        tests:
          - not_null

      - name: encounter
        description: Clinical encounter ID
        tests:
          - not_null

      - name: recorded_date
        description: Date of diagnosis
        tests:
          - is_date:
              date_format: yyyy-mm-dd

      - name: code
        description: Diagnosis code
        tests:
          - not_null

      - name: onset_datetime
        description: Onset date of the diagnosis
        tests:
          - is_date:
              date_format: yyyy-mm-dd
      
      - name: abatement_datetime
        description: Date the diagnosis was resolved
        tests:
          - is_date:
              date_format: yyyy-mm-dd

      - name: code_system
        description: The code system that defines the diagnosis code

      - name: service_date
        description: Service date
        tests:
          - is_date:
              date_format: yyyy-mm-dd

      - name: created_timestamp
        description: Timestamp of when the diagnosis record was created
        tests:
          - not_null
          - is_date:
              date_format: yyyy-mm-dd HH24:MI:SS
              date_type: timestamp

      - name: modified_timestamp
        description: Timestamp of when the diagnosis record was last modified
        tests:
          - not_null
          - is_date:
              date_format: yyyy-mm-dd HH24:MI:SS
              date_type: timestamp

      - name: client_id
        description: Strive client ID
        tests:
            - not_null
            - accepted_values:
                values: ['ssm']

      - name: ingest_date
        description: Strive ingest date
        tests:
          - not_null
          - is_date:
              date_format: yyyy-mm-dd HH24:MI:SS
