create table raw_ssm.labs(
    patient_id varchar(255),
    patient_account_number varchar(255),
    clinical_encounter_id varchar(255),
    lab_id varchar(255),
    lab_code_set varchar(255),
    lab_code varchar(255),
    lab_order_date timestamp,
    lab_order_description varchar(255),
    service_code varchar(255),
    service_code_modifier varchar(255),
    service_code_type varchar(255),
    service_code_desc varchar(255),
    result_description varchar(255),
    collection_date timestamp,
    result_date timestamp,
    result_text varchar(255),
    result_numeric numeric(18,4),
    result_pos_neg varchar(255),
    unit varchar(255),
    reference_range varchar(255),
    abnormal_flag varchar(255),
    result_status varchar(255),
    created_timestamp timestamp,
    modified_timestamp timestamp
);