create table ssm.medication (
    patient_id varchar(255),
    patient_account_number varchar(255),
    clinical_encounter_id varchar(255),
    medication_origin_id varchar(255),
    medication_code_set varchar(255),
    medication_code varchar(255),
    medication_description varchar(255),
    medication_begin_date timestamp,
    medication_end_date timestamp,
    days_supply varchar(255),
    quantity varchar(255),
    refills int,
    strength varchar(255),
    strength_unit varchar(255),
    formulation varchar(255),
    route varchar(255),
    frequency varchar(255),
    dosage varchar(255),
    med_status varchar(255),
    sample varchar(255),
    created_timestamp timestamp,
    modified_timestamp timestamp
);